# see https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
version=${pom.version}
timestamp=${maven.build.timestamp}
spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.database=credit-card
spring.jackson.serialization.indent_output=true
server.compression.enabled=true
server.compression.mime-types=application/json,application/hal+json
